#!bin/bash
#Sctipt de Arranque de Peter
#chkconfig: 3 51 02
#description: Servicio de Peter
 echo "Seteando variables de entorno"
 export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
 export PATH=$PATH:$JAVA_HOME/bin
 PROGRAMA=/home/directorio
 STARTUP=$PROGRAMA/ejecutar.sh
 PID_PATH_NAME=/tmp/demonioFile-pid
 SERVICE_NAME=demonioFile

 start(){ 
 echo -n $"starting service $SERVICE_NAME ..."
 $STARTUP
 RETVAL=$?
 echo
 }

 case "$1" in
	start)
	if [ ! -f $PID_PATH_NAME ]; then
	  start
	   echo "el servicio $SERVICE_NAME se inicio con exito" 
	else 
         echo "el servicio $SERVICE_NAME ya se encuentra iniciado"
	 fi ;;
	stop)
	if [ -f $PID_PAHT_NAME ]; then
	 PID=$(cat $PID_PATH_NAME);
	  echo "detenientdo $SERVICE_NAME ... "
          kill $PID;
          echo "$SERVICE_NAME se ha detenido"
          rm $PID_PATH_NAME
	else 
         echo "el servicio $SERVICE_NAME no se encuentra iniciado"
	 fi ;;
	 *)
	 echo "Uso $SERVICE_NAME start/stop"
 	exit 1;;
 esac
 exit 0
